security:
    providers:
        app_user_provider:
            id: App\Security\UserProvider
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        public:
            pattern: ^/sign-in
            security: false
            methods: [GET]
        handle_sign_in:
            pattern: ^/sign-in
            methods: [POST]
            custom_authenticators:
                - App\Security\CredentialAuthentication\Authenticator
        secured:
            pattern: ^/
            lazy: true
            provider: app_user_provider
            custom_authenticators:
                - App\Security\TokenAuthentication\Authenticator
            entry_point: App\Security\TokenAuthentication\AuthenticationEntryPoint
            logout:
                path: log_out_handle
    access_control:
        - { path: ^/, roles: ROLE_USER }
