controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

sign_in_handle:
    path: !php/enum App\Enum\Routes::SIGN_IN_VIEW_PATH->value
    methods: [POST]
