controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

sign_in_view:
    path: '/sign-in/'
    methods: [GET]
    controller: App\Controller\SignInController::view

sign_in_handle:
    path: '/sign-in/'
    methods: [POST]
