parameters:
  test_authentication_provider_bundle_frontend_token_provider_users:
    'user@example.com': 'password'

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Tests\Services\ApplicationClient\ClientFactory:
    public: true

  SmartAssert\SymfonyTestClient\SymfonyClient:
    public: true

  app.tests.integration.http.client:
    public: true
    class: GuzzleHttp\Client
    arguments:
      $config:
        base_uri: "https://localhost/"
        verify: false

  SmartAssert\SymfonyTestClient\HttpClient:
    public: true
    arguments:
      $httpClient: '@app.tests.integration.http.client'

  App\Tests\Services\SessionHandler:
    public: true
    arguments:
      $sessionFactory: '@session.factory'

  App\Tests\Services\CookieExtractor:
    public: true

  App\Tests\Services\Credentials:
    public: true
